// mostly generated by Claude Code when I gave it styling requirements
// I added the add to queue elements

import { memo } from 'react'
import type { Track } from '../types/track'
import styles from '../styles/TrackItem.module.css'
import { ListPlus } from 'lucide-react'

interface TrackItemProps {
    track: Track
    onPlay: (track: Track) => void
    onAddToQueue: (track: Track) => void
}

function formatDuration(seconds: number): string {
    const m = Math.floor(seconds / 60)
    const s = seconds % 60
    return `${m}:${s.toString().padStart(2, '0')}`
}

const TrackItem = memo(function TrackItem({ track, onPlay, onAddToQueue }: TrackItemProps) {
    return (
        <div className={styles.row}>
            {/* disable play and add to queue buttons if the song is not readable, is missing a preview, or contains explicit lyrics */}
            <button 
                className={styles.playButton} 
                disabled={!track.readable || !track.preview || track.explicit_lyrics}
                onClick={() => onPlay(track)}
                aria-label={`Play ${track.title}`}
            >
                ▶
                {/* TODO: mark as pause if the song is playing */}
            </button>
            <span className={styles.title}>{track.title}</span>
            <span className={styles.duration}>{formatDuration(track.duration)}</span>
            <button 
                className={styles.queueButton} 
                disabled={!track.readable || !track.preview || track.explicit_lyrics}
                onClick={() => onAddToQueue(track)}
                aria-label={`Add ${track.title} to queue`}
            >
                <ListPlus size={16}/>
            </button>
        </div>
    )
})

export default TrackItem
